version: '3.7'
services:
  nps:
    image: sxxpqp/nps
    container_name: nps
    privileged: true
    restart: always
    ports:
      - 8024:8024  # NPS service internal port for TCP bridging
    network_mode: "host"
    volumes:
      - /opt/nps/conf:/conf
