
version: '3.7'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    volumes:
      -  /mnt/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Xl123456..  
    networks:
      - web
    command: server /data --console-address ":9001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio.sxxpqp.top`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.tls.certresolver=myresolver"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minioapi.rule=Host(`minioapi.sxxpqp.top`)"
      - "traefik.http.routers.minioapi.entrypoints=websecure"
      - "traefik.http.routers.minioapi.tls=true"
      - "traefik.http.routers.minioapi.tls.certresolver=myresolver"
      - "traefik.http.services.minioapi.loadbalancer.server.port=9001"
networks:
  web:
    external: true
